### ISSUE TITLE
Ajustes no tema

### ISSUE THREAD

**Issue by uira** [ForaDoEixo/arquivo#2]
LAYOUT NEWS/REPORTAGEM TEMPORÁRIO

- [ ] padronizar fontes e estilos identico ao dos colunistas H1, H2, H3, quote, etc
- [ ] ajuste da largura da coluna para 800px no titulo e foto destaque e 600px no corpo do texto -> @iwasthesword
- [ ] legendas das fotos > o arquivo deve importar a legenda do Alt text para ficar como legenda (ref. colunistas)
- [ ]  imagem destacada nao funciona no embed interno do site (pagina do autor)- no embed de face ta perfeito
- [ ] embedar conteudos de twitter, facebook e youtube automaticamente, só aparece o link
- [ ] as fotos de perfil e imagem destacada do post também não foram
- [ ] rodapé desconfigurado (manter padrão colunistas)
- [ ] não importou as imagens e descrição do autor na pagina de autor
- [ ] os box de citação do oximity vieram como negrito e itálico pro site novo, configurar como h4 (Fonte menor e com menos espacamento)

**Comment by raissagal** [comment]
O post tá com 2 templates, um com a coluna fina e outro preenchendo a coluna toda
quando abre o link direto:
![captura de tela 2017-05-15 as 14 16 06](https://cloud.githubusercontent.com/assets/14958399/26069952/331ad618-3979-11e7-9fc0-573c6e98a64c.png)
quando ele vem na sequeência da rolagem dos outros posts:
![captura de tela 2017-05-15 as 14 16 16](https://cloud.githubusercontent.com/assets/14958399/26069947/2ee7b336-3979-11e7-9f4d-561321290e9e.png)

**Comment by xaiki** [comment]
@uira isso ta feito ?? se pode fechar ?

**Comment by uira** [comment]
@iwasthesword dá um confere pra resolver e fechar todas as issues relacionadas a CSS, pode ser?

**Comment by iwasthesword** [comment]
essas alterações foram feitas todas no redeninja, ja que esse tema não está nem sendo usado. talvez deletar isso aqui?
